version: "3.5"

services:
  frontend:
    image: front
    ports:
      - 5000:5000
    depends_on:
      - redis
  backend:
    image: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=mooc
    ports:
      - 8080:8080
  redis:
    image: redis
    ports:
      - 6379:6379
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres_db3
    environment:
      - POSTGRES_PASSWORD=mooc
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./database/logs:/var/log/postgresql
    depends_on:
      - backend
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NGINX_HOST=http://localhost
      - NGINX_PORT=80
    depends_on:
      - backend
      - frontend
      - db
      - redis
