version: "3.5"
services:
  frontend:
    image: front
    ports:
      - 5000:5000

  backend:
    image: backend
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=mooc
      - DB_NAME=mooc
      - DB_HOST=db
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: mooc
