version: "3.5"
services:
  backend:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - "FRONT_URL=http://localhost:5000"
      - "REDIS_HOST=redis"

  redis:
    image: redis
    ports:
      - "6379:6379"

  frontend:
    image: front
    ports:
      - "5000:5000"
    environment:
      - "API_URL=http://localhost:8080"
